---
section_name: 
page_heading_margin_in_lines: 3
ad_type: no_ad
is_front_page: false
profile: 7x15_7
section_id: 12
page_columns: 7
grid_size:
- 146.99662542182014
- 97.32283464566807
lines_per_grid: 7.0
width: 1114.01574803148
height: 1544.88188976376
left_margin: 42.5196850393695
top_margin: 42.5196850393695
right_margin: 42.5196850393695
bottom_margin: 42.5196850393695
gutter: 12.7559055118108
story_frames:
- - 0
  - 0
  - 7
  - 8
- - 0
  - 8
  - 3
  - 4
- - 3
  - 8
  - 2
  - 4
- - 5
  - 8
  - 2
  - 4
- - 0
  - 12
  - 2
  - 3
- - 2
  - 12
  - 3
  - 3
- - 5
  - 12
  - 2
  - 3
article_line_thickness: 0.3
draw_divider: 
date: '2017-05-30'
